# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Toontagram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Toontagram
pod 'SnapKit', '~> 5.0.1'
pod 'SDWebImage', '~> 5.0'

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'Firebase/Messaging'
pod 'Firebase/Auth'
pod 'ActiveLabel'
pod 'JGProgressHUD','~>2.0.3'
pod 'YPImagePicker'
pod 'Instructions', '~> 2.1.1'
end
